# Basic site info
title:              "heiswayi.nrird.com •••"
description:        "A Personal Blog of Heiswayi Nrird"
keywords:           "heiswayi nrird, personal blog, software engineer, life experience, technology and research"
logo_text:          "heiswayi.nrird.com"
show_tagline:       true # edit file in /_includes/tagline.html
show_social_icons:  false # edit file in /_includes/social_links.html
og_locale:          "en_US"
cover:              "/assets/logo.gif" # site image cover
version:            "2018.7.15"

# Improving site SEO
seo_title:          "heiswayi.nrird.com // a personal blog of heiswayi nrird" # between 55 and 66 characters
seo_description:    "Hi. I'm Heiswayi Nrird. I do some stuffs with computer and sometimes write about it here. I'm a Software Engineer from Penang and I ship code at Keysight Technologies." # between 70 and 300 characters

# Site URL settings
url:                https://heiswayi.nrird.com # main url
baseurl:            null # for gh-pages
enforce_ssl:        heiswayi.nrird.com
github_post_dir:    https://github.com/heiswayi/heiswayi.github.io/blob/master/

# Site author info
author:
  name:             "Heiswayi Nrird"
  email:            hnrird@gmail.com
  github_username:  heiswayi
  twitter_username: heiswayi
  facebook_url:     

# Display related post?
related_post_enabled: true

# Enable post sharer?
post_sharer: false

# Disqus comment settings
disqus_enabled:     false
disqus_shortname:   hnbloggithub

# Google Analytics ID
google_analytics_code: UA-58296043-7

# Build settings
source:             ./
destination:        ./_site
permalink:          /:year/:title
markdown:           kramdown
highlighter:        rouge
timezone:           Asia/Kuala_Lumpur
exclude:            [
                      "README.md",
                      "LICENSE.md",
                      "CHANGELOG.md",
                      "TODO.md",
                      "DRAFT-*.html",
                      "gulpfile.js",
                      "node_modules",
                      "package.json"
                    ]

# Site configurations
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
  ignore:
    envs:           [local]
  blanklines:       false
  profile:          false
  startings:        [html, head, body]

sass:
  sass_dir:         assets/_scss
  style:            compressed # expanded

plugins:
  - jekyll-sitemap
  - jekyll-autoprefixer

autoprefixer:
  browsers:
  - last 3 version