# SITE INFO
og_locale               : "en_US"
title                   : "Heiswayi Nrird"
description             : "Welcome to Heiswayi Nrird's Personal Webpage" # tagline
keywords                : "software engineering, user experience, open source, photography, random experimental stuff"
image_cover             : "/assets/cover.gif"
version                 : "2020"
google_analytics_code   : UA-58296043-7

# SITE SEO FOR GOOGLE SEARCH
seo_title               : "Heiswayi Nrird" # between 55 and 66 characters
seo_description         : "Hi, I'm Heiswayi Nrird. I'm a software engineer and I ship software at Keysight Technologies, Penang, MY. I do blog occasionally. I'm a minimalist and I believe in 'less is more'. Sometimes, I do some random stuff and write about it here. /\\/" # between 70 and 300 characters

# SITE URL
url                     : https://heiswayi.nrird.com # main url
baseurl                 : null # for github-pages only

# GitHub Pages ONLY
enforce_ssl             : heiswayi.nrird.com

# AUTHOR INFO
author:
  name                  : "Heiswayi Nrird"
  twitter_username      : heiswayi

# ARTICLE BOTTOM MODULES
show_related_posts      : false
show_post_sharer        : false
show_tags               : false

show_disqus_comment     : false
disqus_shortname        : hnbloggithub

show_postlist_alt_view  : false

# JEKYLL BUILD SETTINGS
source                  : ./
destination             : ./_site
permalink               : /:title
markdown                : kramdown
highlighter             : rouge
timezone                : Asia/Kuala_Lumpur

include:
  - _redirects

exclude:
  - README.md
  - LICENSE.md
  - CHANGELOG.md
  - TODO.md
  - "DRAFT-*.html"
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - "*.gemspec"
  - "*.psd"
  - logo.png

compress_html:
  clippings             : all
  comments              : ["<!-- ", " -->"]
  endings               : all
  ignore:
    envs                : [local]
  blanklines            : false
  profile               : false
  startings             : [html, head, body]

sass:
  sass_dir              : assets/_scss
  style                 : compressed # or expanded

plugins:
  - jekyll-sitemap
  - jekyll-autoprefixer

autoprefixer:
  browsers:
  - last 3 version