# Basic site info
og_locale:          "en_US"
title:              "heiswayi.nrird.com"
description:        "heiswayi nrird's personal blog" # tagline
keywords:           "software engineer, web developer, personal website, code snippet, php, c#, powershell, build automation, .net framework, programmer, ui/ux"
logo_text:          "hn•••" # if using text as site heading logo
cover:              "/assets/logo.gif"
version:            "2019.11.2" # CSS version tag, used with CHANGELOG.md

# Site SEO
seo_title:          "heiswayi nrird's personal blog" # between 55 and 66 characters
seo_description:    "I'm Heiswayi Nrird. I do some stuffs with computer and sometimes write about it here. I'm a Software Engineer and I ship code at Keysight Technologies." # between 70 and 300 characters

# Site URL
url:                https://heiswayi.nrird.com # main url
baseurl:            null # for gh-pages only

# GitHub Pages ONLY
enforce_ssl:        heiswayi.nrird.com

# Site author info
author:
  name:             "Heiswayi Nrird"
  twitter_username: heiswayi

# Display tagline on site header?
show_tagline: false # edit file in /_includes/tagline.html

# Display social icons on site header?
show_social_icons: false # edit file in /_includes/social_links.html

# Display related post at the bottom of a post?
related_post_enabled: false

# Enable post sharer text at the bottom of article?
post_sharer: false

# Disqus comment settings
disqus_enabled:     false
disqus_shortname:   hnbloggithub

# Google Analytics ID
google_analytics_code: UA-58296043-7

# Jekyll build settings
source:             ./
destination:        ./_site
permalink:          /:title
markdown:           kramdown
highlighter:        rouge
timezone:           Asia/Kuala_Lumpur

include:
  - _redirects

exclude:
  - README.md
  - LICENSE.md
  - CHANGELOG.md
  - TODO.md
  - "DRAFT-*.html"
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - "*.gemspec"

compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
  ignore:
    envs:           [local]
  blanklines:       false
  profile:          false
  startings:        [html, head, body]

sass:
  sass_dir:         assets/_scss
  style:            compressed # expanded

plugins:
  - jekyll-sitemap
  - jekyll-autoprefixer

autoprefixer:
  browsers:
  - last 3 version