# LOCALE
og_locale               : "en_US"
locale                  : "en_US"

# SITE METADATA
title                   : "Heiswayi Nrird"
tagline                 : "Your limitation — it's only your imagination." # short description
description             : "Software Engineering · UI/UX · DevOps · OSS · Artificial Intelligence" # long description
keywords                : "software engineering, user experience, open source, photography, random experimental stuff"
image_cover             : "/assets/cover.gif"
logo                    : "/assets/cover.gif"
version                 : "20210122"

# SITE OWNERSHIP VERIFICATIONS
webmaster_verifications:
  google                : "aSavCGGU0uSN5HEHnI7ZiMqVKxn7mfUPCGMVJvmDQ1w"
  bing                  : null
  alexa                 : null
  yandex                : "13f3a6696f133a01"
  baidu                 : null

# SITE URL
url                     : https://heiswayi.nrird.com # main url
baseurl                 : null # for github-pages only

# AUTHOR INFO
author:
  name                  : "Heiswayi Nrird"

# SOCIAL MEDIA
twitter:
  username              : heiswayi
  card                  : summary
facebook:
  app_id                : null
  publisher             : null
  admins                : null
social:
  name                  : "Heiswayi Nrird"
  links:
    - https://twitter.com/heiswayi
    - https://github.com/heiswayi
    - https://my.linkedin.com/in/nrird
    - https://codepen.io/heiswayi/
    - https://keybase.io/heiswayi
    - https://unsplash.com/@heiswayi_nrird
    - https://gist.github.com/heiswayi
    - https://jsfiddle.net/user/heiswayi/

# ARTICLE BOTTOM MODULES
show_related_posts      : false
show_post_sharer        : false
show_tags               : true
show_disqus_comment     : false
disqus_shortname        : hnbloggithub

# JEKYLL BUILD SETTINGS
source                  : ./
destination             : ./_site
permalink               : /:title
markdown                : kramdown
highlighter             : rouge
timezone                : Asia/Kuala_Lumpur

include:
  - _redirects

exclude:
  - README.md
  - LICENSE.md
  - CHANGELOG.md
  - TODO.md
  - "DRAFT-*.html"
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - "*.gemspec"
  - "*.psd"
  - logo.png

compress_html:
  clippings             : all
  comments              : ["<!-- ", " -->"]
  endings               : all
  ignore:
    envs                : [local]
  blanklines            : false
  profile               : false
  startings             : [html, head, body]

sass:
  sass_dir              : assets/_scss
  style                 : compressed # or expanded

plugins:
  - jekyll-sitemap
  - jekyll-autoprefixer
  - jekyll-purgecss
  - jekyll-seo-tag

autoprefixer:
  browsers:
  - last 3 version

css_dir: assets/css