# SITE METADATA
title                   : "Heiswayi Nrird"
tagline                 : "Heiswayi Nrird - Software Engineer" # jekyll-seo-tag
description             : "Learning · Programming · Simplifying"
keywords                : "frontend developer, ux designer, human-factor engineering, open source, photography, programming"
logo                    : "/assets/cover.gif" # jekyll-seo-tag
version                 : "23.03.21"

# SITE OWNERSHIP VERIFICATIONS
webmaster_verifications:
  google                : "aSavCGGU0uSN5HEHnI7ZiMqVKxn7mfUPCGMVJvmDQ1w"
  bing                  : null
  alexa                 : null
  yandex                : "13f3a6696f133a01"
  baidu                 : null
  wot                   : "5cf878109d0d39f281fd"

# SITE URL
baseurl                 : "" # main url, jekyll-seo-tag

# AUTHOR INFO
author:
  name                  : "Heiswayi Nrird"
  url                   : https://heiswayi.nrird.com

# SOCIAL MEDIA
twitter:
  username              : heiswayi
  card                  : summary
facebook:
  app_id                : null
  publisher             : null
  admins                : null
social:
  name                  : "Heiswayi Nrird"
  links:
    - https://twitter.com/heiswayi
    - https://github.com/heiswayi
    - https://my.linkedin.com/in/heiswayi
    - https://codepen.io/heiswayi/
    - https://keybase.io/heiswayi
    - https://unsplash.com/@heiswayi_nrird
    - https://gist.github.com/heiswayi
    - https://jsfiddle.net/user/heiswayi/

# ARTICLE BOTTOM MODULES
show_tags               : true

# JEKYLL BUILD SETTINGS
source                  : ./
destination             : ./_site
permalink               : /:title
markdown                : kramdown
highlighter             : rouge
timezone                : Asia/Kuala_Lumpur

include:
  - _redirects

exclude:
  - README.md
  - LICENSE.md
  - CHANGELOG.md
  - TODO.md
  - "DRAFT-*.html"
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - "*.gemspec"
  - "*.psd"
  - Dockerfile

compress_html:
  clippings             : all
  comments              : ["<!-- ", " -->"]
  endings               : all
  ignore:
    envs                : [local]
  blanklines            : false
  profile               : false
  startings             : [html, head, body]

sass:
  sass_dir              : assets/_scss
  style                 : compressed # or expanded

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path:            resume.pdf
    values:
      sitemap:         false
  - scope:
      path:            markdown-test.md
    values:
      sitemap:         false